version: '0.1'
services:
  eureka:
    container_name: eureka-server
    image: chuyuxuan/eurekaserver
    ports:
      - "8761:8761"


  client:
    image: chuyuxuan/client2
    ports: 
      - "8082:8082"
    links:
      - eureka
    restart: always