eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083
spring:
  application:
    name: security-client
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9098/user
    client:
      id: client_2
      access-token-uri: http://localhost:9098/oauth/token
      grant-type: authorization_code
      scope: app